### ISSUE TITLE
Latest version fails to post any data

### ISSUE THREAD

**Issue by Bishbulb** [surgicalcoder/Tether#4]
We just tried running version 2.0.58 on a Windows Server 2012 R2 machine, and observed that the plugin fails to post any data. Checking the errors logs, it has a HTML error page stating that "you must have javascript enabled". I'm pretty sure there the request is being sent without any authorization, and ServerDensity is forcing a redirect to their login page (which then returns the Javascript error).

**Comment by surgicalcoder** [comment]
Have the settings been set correctly in your settings.json file? Did you run it through the Tether.Installer project or manually set it up?

**Comment by Bishbulb** [comment]
@surgicalcoder Yes I'm using the exact same settings.json file as version 1.0.34 (aside from the new default properties that were added in 2.0.58). I uninstalled the old Tether instance via `Tether.exe uninstall`, then installed the new instance via `Tether.exe install` (both were run from a Powershell console). 

What other information can I provide that would help diagnose this issue?

**Comment by surgicalcoder** [comment]
@Bishbulb My apologies, I forgot to update the default postback URL in the documentation (fixed now), it should be in this format:

https://{account}.agent.serverdensity.io/intake/?agent_key={agentkey}

Tether no longer appends or adds anything (in the code) to the postback URL, which is a change from v1. Please let me know if this fixes the issue for you.

**Comment by Bishbulb** [comment]
@surgicalcoder I applied the changes to the settings.json file, and the agent is working properly now. Thank you!
